### ISSUE TITLE
where did u get the executable file jenny?

### ISSUE THREAD

**Issue by luckypoem** [hmngwy/jenny#2]
hi.

i setup a blog as per ur repo: http://jny.bright.biz.st/ ,i did it this way:
cd /usr/local

git clone https://github.com/hmngwy/jenny jenny-site
cd jenny-site

root@AR:/usr/local/jenny-site# mkdir dist
root@AR:/usr/local/jenny-site# echo "DIST=dist" >> .blogrc
root@AR:/usr/local/jenny-site# nano 2017-02-24-test-1.md
root@AR:/usr/local/jenny-site# cat 2017-02-24-test-1.md
# 测试1
tags: misc1 misc2 misc3

这是测试1.

看看如何？
root@AR:/usr/local/jenny-site# ./jenny

but i wonder how u generated the executable file jenny?
tks

**Comment by hmngwy** [comment]
The executable will be installed to /usr/local/bin by executing `make install`, you don't have to clone the source into /usr/local. 

Your blog and dist directories doesn't have to be in the same directory as the source code. 

Here's a series of commands that is the recommended use-case scenario, $ indicates a single command, this might not be accurate but you should get the idea:

```
# Clone the source
$ mkdir ~/Forks
$ git clone  https://github.com/hmngwy/jenny ~/Forks/jenny

# Installs script to /usr/local/bin
$ (cd ~/Forks/jenny; make install)

# Create the blog
$ mkdir ~/blog
$ echo "DIST=~/blog/.dist" >> ~/blog/.blogrc

# Create a published post
$ cat <<EOT >> "~/blog/$(date +%Y-%m-%d) first-post.md" \
# Hello World\
\
Jenny is a static blog generator using bash, sed, and awk.\
EOT

# Generate the blog
$ jenny
```

**Comment by hmngwy** [comment]
Closed for inactivity
