### ISSUE TITLE
gawk regexp escape sequence is not a known regexp operator

### ISSUE THREAD

**Issue by alexmat** [hmngwy/jenny#28]
fresh install from master branch:

```
$ jenny
[jenny] Sourced .blogrc
[jenny] Generating main index
[jenny] ☶ 2020-03-13 hello-world.md
gawk: ~/.local/share/jenny/lib/md2html.awk:30: warning: regexp escape sequence `\!' is not a known regexp operator
gawk: ~/.local/share/jenny/lib/md2html.awk:109: warning: regexp escape sequence `\"' is not a known regexp operator
```

```
$ awk --version
GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
```

**Comment by hmngwy** [comment]
I'm not able to replicate this, on the same version of gawk. Let me know if this issue persists.

**Comment by hmngwy** [comment]
Found it, it is an incompatibility with gawk 5.0.1, similar discovery here: https://github.com/KittyKatt/screenFetch/issues/627

Temporary fix is to downgrade to gawk 4.x.x. Contemplating whether I should vendor in a different script like Gruber's markdown.pl (thus breaking older jenny sites), or simply update this one.

**Comment by hmngwy** [comment]
Closing, moving forward everyone is recommended to bring in their own markdown parser. This is beyond the role of jenny.
