### ISSUE TITLE
md2html.awk dead link

### ISSUE THREAD

**Issue by oxr463** [hmngwy/jenny#29]
Dead link: https://bitbucket.org/yiyus/md2html.awk

**Comment by fr-an-kh** [comment]
@oxr463 have you been able to solve the problem somehow?

**Comment by oxr463** [comment]
> @oxr463 have you been able to solve the problem somehow?

Nope.

**Comment by fr-an-kh** [comment]
@oxr463 just saw that the file is here in the repository:
https://github.com/hmngwy/jenny/blob/master/share/jenny/lib/md2html.awk
