### ISSUE TITLE
How about built in `jenny create`?

### ISSUE THREAD

**Issue by oprizal** [hmngwy/jenny#31]
Hi, `jenny` is simple awesome!

Btw, it will be convenient if `jenny` have build in command like `jenny create` to create post. Something like `jenny` on `make install` will check default `$EDITOR` on terminal `env`. If not exist then offering the default editor to use---together with other setup during `make install`.

This command `jenny create` will ask for title then automatically create `*.md` file with name contain current date and title then open this file with default $EDITOR.

It's must be very helpful for people---like me---who uses eleven finger to type (mostly use index fingers only). :))

Even though I'm already create custom script for my need, but it's would be nice if `jenny` have this kind build in command.

**Comment by hmngwy** [comment]
Maybe you can incorporate your script to the codebase and send a PR? :)

**Comment by hmngwy** [comment]
In hindsight, this is beyond the role of jenny. Closing.
