### ISSUE TITLE
Path error during deployment / Installation issue

### ISSUE THREAD

**Issue by smartmic** [hmngwy/jenny#4]
There is a path issue, inserting bin/ before share/ when running `jenny`, see my output:
```
$ jenny
Working in /home/martin/website/jennyblog/.dist
• Skipping: 2018-05-18 first-post.md
  - post/first-post.html
CREATED PAGE 1

/usr/local/bin/jenny: line 215: /usr/local/bin/share/layout/index.sh: No such
file or directory
Generating feed.xml

/usr/local/bin/jenny: line 223: /usr/local/bin/share/layout/rss2.sh: No such file or directory
ls: cannot access /tmp/jennytag_*: No such file or directory
```

**Comment by hmngwy** [comment]
@smartmic just so I could estimate what you're getting for `$LAYOUT_DIR`. 

1. Did you install using `make install` or did you symlink?
2. Are you running it on macOS or Linux?

**Comment by smartmic** [comment]
@hmngwy Thanks for the fast response, (1) I installed it by `make install` on (2) Debian Linux. The `layout/` and `lib/` directories are actually under ` /usr/local/share/jenny/`. Seems that there is some misalignment with paths on my installation…

**Comment by hmngwy** [comment]
@smartmic can you try out bugfix/4 (#5)? would be best if you can try to do so with a clean install. So, clear the /tmp files, delete the existing installation.

I tried it out on a fresh debian docker container, it worked for me.

**Comment by hmngwy** [comment]
@smartmic Ah hold that, I didn't address it just yet in those commits.

**Comment by hmngwy** [comment]
@smartmic ok, please try this commit https://github.com/hmngwy/jenny/pull/5/commits/66dc2565a9dbd1eadde5342067d30dd89e118ccb

**Comment by smartmic** [comment]
@hmngwy many thanks! This solved it for me.
